title: Yishuo Meng's Homepage
page-top-title: Yishuo Meng
top-section-bg-text: AI Accelerator
backgrounds:
  - static/assets/background/background_0.jpg
  - static/assets/background/background_1.jpg
background-interval-ms: 7000
background-overlay: 0.52
copyright-text: '&copy; Yishuo Meng 2023-2026. All Rights Reserved.'
sections:
  - id: home
    nav: HOME
    title: Yishuo Meng | 孟依烁
    href: '#page-top' # Default to '#<id>' if not specified
  - id: publications
    nav: PUBLICATIONS
    title: PUBLICATIONS
    icon: bi-file-text-fill
  - id: awards
    nav: AWARDS
    title: AWARDS
    icon: bi-award-fill
